package com.andlill.jfd.model

import java.io.Serializable

class Sense : Serializable {
    val dialect : ArrayList<Dialect> = ArrayList()
    val field : ArrayList<Field> = ArrayList()
    val glossary : ArrayList<String> = ArrayList()
    val misc : ArrayList<Misc> = ArrayList()
    val partOfSpeech : ArrayList<PartOfSpeech> = ArrayList()
    val usage : ArrayList<String> = ArrayList()

    enum class Dialect(val description: String) {
        Brazilian("Brazilian"),
        Hokkaido("Hokkaido-ben"),
        Kansai("Kansai-ben"),
        Kantou("Kantou-ben"),
        Kyoto("Kyoto-ben"),
        Kyuushuu("Kyuushuu-ben"),
        Nagano("Nagano-ben"),
        Osaka("Osaka-ben"),
        Ryuukyuu("Ryuukyuu-ben"),
        Touhoku("Touhoku-ben"),
        Tosa("Tosa-ben"),
        Tsugaru("Tsugaru-ben"),
        Unclassified("Unclassified"),
    }

    enum class Field(val description: String) {
        Agriculture("Agriculture"),
        Anatomy("Anatomy"),
        Archeology("Archeology"),
        Architecture("Architecture"),
        Art("Art"),
        Astronomy("Astronomy"),
        Audiovisual("Audiovisual"),
        Aviation("Aviation"),
        Baseball("Baseball"),
        Biochemistry("Biochemistry"),
        Biology("Biology"),
        Botany("Botany"),
        Buddhism("Buddhism"),
        Business("Business"),
        Chemistry("Chemistry"),
        Christianity("Christianity"),
        Clothing("Clothing"),
        Computing("Computing"),
        Crystallography("Crystallography"),
        Ecology("Ecology"),
        Economics("Economics"),
        Electricity("Electricity"),
        Electronics("Electronics"),
        Embryology("Embryology"),
        Engineering("Engineering"),
        Entomology("Entomology"),
        Finance("Finance"),
        Fishing("Fishing"),
        Food("Food"),
        Gardening("Gardening"),
        Genetics("Genetics"),
        Geography("Geography"),
        Geology("Geology"),
        Geometry("Geometry"),
        Golf("Golf"),
        Grammar("Grammar"),
        GreekMythology("Greek Mythology"),
        HorseRacing("Horse Racing"),
        Law("Law"),
        Linguistics("Linguistics"),
        Logic("Logic"),
        MartialArts("Martial Arts"),
        Mahjong("Mahjong"),
        Mathematics("Mathematics"),
        MechanicalEngineering("Mechanical Engineering"),
        Medicine("Medicine"),
        Meteorology("Meteorology"),
        Military("Military"),
        Music("Music"),
        Ornithology("Ornithology"),
        Paleontology("Paleontology"),
        Pathology("Pathology"),
        Pharmacy("Pharmacy"),
        Philosophy("Philosophy"),
        Photography("Photography"),
        Physics("Physics"),
        Physiology("Physiology"),
        Printing("Printing"),
        Psychiatry("Psychiatry"),
        Psychology("Psychology"),
        Railway("Railway"),
        Shinto("Shinto"),
        Shogi("Shogi"),
        Sports("Sports"),
        Statistics("Statistics"),
        Sumo("Sumo"),
        Telecommunications("Telecommunications"),
        Trademark("Trademark"),
        VideoGames("Video Games"),
        Zoology("Zoology"),
        Unclassified("Unclassified"),
    }

    enum class Misc(val description: String) {
        Abbreviation("Abbreviation"),
        Archaism("Archaism"),
        Character("Character"),
        Children("Children's Language"),
        Colloquialism("Colloquialism"),
        Company("Company Name"),
        Creature("Creature"),
        Dated("Dated"),
        Deity("Deity"),
        Derogatory("Derogatory"),
        Document("Document"),
        Event("Event"),
        Familiar("Familiar Language"),
        Female("Female Language"),
        Fiction("Fiction"),
        Formal("Formal"),
        Given("Given Name"),
        Group("Group"),
        Historical("Historical"),
        Honorific("Honorific Language"),
        Humble("Humble Language"),
        Idiomatic("Idiomatic"),
        Jocular("Humorous"),
        Legend("Legend"),
        Manga("Manga Slang"),
        Male("Male Language"),
        Mythology("Mythology"),
        Internet("Internet Slang"),
        Object("Object"),
        Obsolete("Obsolete"),
        Obscure("Obscure"),
        Onomatopoeic("Onomatopoeic"),
        Organization("Organization"),
        Other("Other"),
        Person("Person"),
        Place("Place"),
        Poet("Poet"),
        Polite("Polite Language"),
        Product("Product Name"),
        Proverb("Proverb"),
        Quote("Quote"),
        Rare("Rare"),
        Religion("Religion"),
        Sensitive("Sensitive"),
        Service("Service"),
        Slang("Slang"),
        Station("Station Name"),
        Surname("Family Name"),
        Kana("Word usually written in kana alone"),
        Vulgar("Vulgar"),
        Work("Work of Art"),
        Yoji("Yojijukugo"),
        Unclassified("Unclassified"),
    }

    enum class PartOfSpeech(val description: String) {
        Adjective("Adjective"),
        AdjectiveAux("Auxiliary Adjective"),
        AdjectiveNa("Na-Adjective"),
        AdjectiveNo("No-Adjective"),
        Adverb("Adverb"),
        Conjunction("Conjunction"),
        Copula("Copula"),
        Counter("Counter"),
        Expression("Expression"),
        Interjection("Interjection"),
        Noun("Noun"),
        NounAdverbial("Adverbial Noun"),
        NounPrefix("Prefix Noun"),
        NounProper("Proper Noun"),
        NounSuffix("Suffix Noun"),
        NounTemporal("Temporal Noun"),
        Numeric("Numeric"),
        Pronoun("Pronoun"),
        Prefix("Prefix"),
        Suffix("Suffix"),
        VerbAux("Auxiliary Verb"),
        VerbIchidan("Ichidan Verb"),
        VerbIrregular("Irregular Verb"),
        VerbIntransitive("Intransitive Verb"),
        VerbKuru("Kuru Verb"),
        VerbGodan("Godan Verb"),
        VerbNidan("Nidan Verb"),
        VerbSuru("Suru Verb"),
        VerbTransitive("Transitive Verb"),
        VerbUnspecified("Unspecified Verb"),
        VerbYodan("Yodan Verb"),
        Unclassified("Unclassified"),
    }
}